'use strict';

/** Comprehensive workflow definitions per demo role profile. */
const PROFILES = [
  {
    id: 'cashier',
    role: 'Cashier',
    login: 'Lariza',
    password: '12345',
    icon: '💳',
    color: '#059669',
    colorLight: '#d1fae5',
    portal: '/portal/cashier',
    hub: '/cashier',
    summary:
      'Financial front line — collect fees, issue payment codes, manage wallets, BetterPay, OPD/IPD/ER settlement, and print receipts.',
    workflows: [
      {
        title: '1. Sign in & open Cashier workspace',
        intro:
          'After login you land on the Cashier portal. Open the Command Center for all payment activity.',
        steps: [
          'Open the HMS URL and sign in with username <strong>Lariza</strong> (case-insensitive).',
          'From the Cashier portal, click <strong>Command Center</strong> or navigate to <code>/cashier</code>.',
          'Review the KPI strip: today\'s revenue, pending queue count, wallet payments.',
          'Use colour-coded tabs: Pending, OPD, IPD, Emergency, Codes Issued, Doctors Rx.',
        ],
        screens: ['login', 'cashier-portal', 'cashier-hub'],
      },
      {
        title: '2. Collect pending payments',
        intro: 'The Pending tab lists tickets awaiting collection from walk-ins and clinical modules.',
        steps: [
          'Search by patient name, ticket number (e.g. <code>PAY-2026-000042</code>), or date.',
          'Click <strong>Collect</strong> on the ticket row to open the settlement screen.',
          'Review line items, insurance co-pay split if applicable.',
          'Select payment method and click <strong>Collect Payment</strong>.',
          'Print receipt and hand payment codes (LAB / RAD / PHARM) to the patient.',
        ],
        screens: ['cashier-hub', 'cashier-settle'],
      },
      {
        title: '3. Issue payment (prepay) for walk-ins',
        intro: 'Use Issue payment when a patient pays before seeing a doctor or receiving a service.',
        steps: [
          'Click <strong>Issue payment</strong> on the Command Center.',
          'Search and select the patient (or arrive via deep link from maternity/OPD).',
          'Choose service type: consultation, laboratory, radiology, maternity, surgery.',
          'Assign doctor if required; apply insurance co-pay % when on file.',
          'Select payment method — for Wallet, verify balance in the prepay modal.',
          'Confirm — ticket appears in Pending or settles immediately.',
        ],
        screens: ['cashier-prepay'],
      },
      {
        title: '4. OPD, IPD & Emergency settlement',
        intro: 'Different tabs handle context-specific billing after clinical activity.',
        steps: [
          '<strong>OPD Payment</strong> — bill unpaid consultation order lines after doctor visit.',
          '<strong>IPD Payment</strong> — settle inpatient account after clinical discharge signed.',
          '<strong>Emergency</strong> — retrospective billing on ER credit tab (no prepayment required).',
          'Use quick code lookup bar for any payment code to jump to settlement.',
        ],
        screens: ['cashier-hub'],
      },
      {
        title: '5. Wallets & cash top-up',
        intro: 'Patient wallets allow prepaid balances deducted at cashier.',
        steps: [
          'Click <strong>Cash Top-up</strong> (after Petty cash payout) on the cashier page.',
          'Search patient by name or ID — select from suggestions.',
          'Enter amount and payment method (Cash / MoMo).',
          'Confirm top-up — wallet balance updates; GL posts to accounting.',
          'For wallet prepay: if balance is insufficient, top up first then retry payment.',
        ],
        screens: ['cashier-wallet', 'cashier-prepay'],
      },
      {
        title: '6. Payment codes & end of day',
        intro: 'Codes verify paid services at Lab, Radiology, and Pharmacy.',
        steps: [
          'Each settled service generates a unique code (e.g. <code>LAB-4829-X7</code>).',
          'Codes Issued tab — search, reprint, audit all generated codes.',
          'Doctors Rx tab — print prescriptions with department codes for patient handoff.',
          'End of day: run EOD reconciliation and sign out on shared computers.',
        ],
        screens: ['cashier-settle'],
      },
    ],
    troubleshooting: [
      ['Code not accepted at lab', 'Confirm ticket is paid; verify correct department code'],
      ['Wallet payment fails', 'Top up wallet; ensure patient has wallet account'],
      ['BetterPay not confirming', 'Patient must complete mobile payment before you confirm'],
    ],
  },
  {
    id: 'doctor',
    role: 'Doctor',
    login: 'Awelsa',
    password: '12345',
    icon: '🩺',
    color: '#1a6bd8',
    colorLight: '#dbeafe',
    portal: '/portal/doctor',
    hub: '/opd-queue',
    summary:
      'Clinical care — OPD consultations, orders, prescriptions, ward rounds, and IPD admissions.',
    workflows: [
      {
        title: '1. Sign in & Doctor portal',
        intro: 'The Doctor portal aggregates your daily clinical workload.',
        steps: [
          'Sign in as <strong>Awelsa</strong> — redirected to <code>/portal/doctor</code>.',
          'Review KPIs: OPD waiting, active consultations, IPD patients.',
          'Use tiles: OPD Queue, New consultation, Ward rounds, Prescriptions.',
        ],
        screens: ['login', 'doctor-portal'],
      },
      {
        title: '2. OPD queue & start consultation',
        intro: 'Patients flow: Registered → Triage (nurse) → Waiting → In consultation → Complete.',
        steps: [
          'Open <strong>OPD Queue</strong> (<code>/opd-queue</code>).',
          'Filter by status: Waiting for doctor, In consultation.',
          'Click <strong>Start consultation</strong> on the next patient.',
          'Review nursing vitals and triage notes on the chart.',
        ],
        screens: ['doctor-opd-queue'],
      },
      {
        title: '3. Consultation documentation',
        intro: 'Record structured clinical notes during the visit.',
        steps: [
          'Document chief complaint, history, examination (SOAP format).',
          'Record diagnosis and clinical impression.',
          'Add clinical notes and attach documents if needed.',
          'Save progress — consultation auto-saves at intervals.',
        ],
        screens: ['doctor-consultation'],
      },
      {
        title: '4. Orders — laboratory & radiology',
        intro: 'Orders require cashier payment before departments process them.',
        steps: [
          'From consultation, click <strong>+ Lab order</strong> or <strong>+ Imaging</strong>.',
          'Select tests from catalog (FBC, Chest X-ray, etc.).',
          'Save orders — patient directed to Cashier for payment.',
          'After payment, Lab/Radiology validate codes and process.',
        ],
        screens: ['doctor-orders'],
      },
      {
        title: '5. Prescriptions & pharmacy',
        intro: 'Electronic prescriptions flow to the pharmacy dispensing queue.',
        steps: [
          'Open prescription panel during or after consultation.',
          'Add medications: drug, dose, frequency, duration.',
          'Check allergies and interactions where displayed.',
          'Click <strong>Save & send to Pharmacy</strong> — appears in pharmacist queue after payment.',
        ],
        screens: ['doctor-rx'],
      },
      {
        title: '6. IPD admissions & ward rounds',
        intro: 'In-patient care extends beyond OPD.',
        steps: [
          'Create <strong>admit order</strong> from patient chart when hospitalization required.',
          'Patient pays deposit at Cashier before ADT assigns bed.',
          'Use <strong>Ward rounds</strong> for daily IPD review and orders.',
          'Sign clinical discharge when ready — enables financial settlement.',
        ],
        screens: ['doctor-portal'],
      },
    ],
    troubleshooting: [
      ['Patient not in queue', 'Front desk must add to OPD queue after consultation fee paid'],
      ['Cannot order lab', 'Save consultation first; verify catalog permissions'],
      ['Prescription not in pharmacy', 'Patient may need to pay pharmacy line at Cashier'],
    ],
  },
  {
    id: 'nurse',
    role: 'Nurse',
    login: 'Ghong',
    password: '12345',
    icon: '💉',
    color: '#ea580c',
    colorLight: '#fff7ed',
    portal: '/portal/nurse',
    hub: '/opd-queue',
    summary: 'Triage, vital signs, OPD queue support, ward care, and IPD nursing workflows.',
    workflows: [
      {
        title: '1. Sign in & Nurse portal',
        intro: 'Nursing portal links triage, vitals, OPD queue, and ward modules.',
        steps: [
          'Sign in as <strong>Ghong</strong> — open <code>/portal/nurse</code>.',
          'Review today\'s OPD volume and ward census KPIs.',
          'Navigate via tiles: OPD triage, Vital signs, Ward board, IPD meds.',
        ],
        screens: ['login', 'nurse-portal'],
      },
      {
        title: '2. OPD triage',
        intro: 'Triage bridges registration and doctor consultation.',
        steps: [
          'Open <strong>OPD Queue</strong> — filter patients in <em>Registered</em> status.',
          'Record chief complaint and nursing assessment.',
          'Set priority (routine, urgent) per protocol.',
          'Update status to <strong>Waiting for doctor</strong> when ready.',
        ],
        screens: ['nurse-triage'],
      },
      {
        title: '3. Vital signs',
        intro: 'Vitals appear on the patient chart for the consulting doctor.',
        steps: [
          'Open patient chart or vitals quick entry from queue.',
          'Record BP, pulse, temperature, SpO₂, respiratory rate, weight, height.',
          'Flag abnormal values per escalation protocol.',
          'Save — vitals timestamped on chart immediately.',
        ],
        screens: ['nurse-vitals'],
      },
      {
        title: '4. Ward board & IPD care',
        intro: 'In-patient nursing supports bed management and medication administration.',
        steps: [
          'Open <strong>Ward board</strong> (<code>/wards</code>) — visual bed status.',
          'Assist ADT with bed assignment after cashier deposit.',
          'Document nursing care plans and ward round notes.',
          'Administer IPD medications per doctor orders; record as given.',
        ],
        screens: ['nurse-ward'],
      },
      {
        title: '5. Sample collection (lab support)',
        intro: 'Nurses may collect samples linked to LIMS requests.',
        steps: [
          'Verify patient identity and lab request on chart.',
          'Collect sample per SOP; label with patient ID and request ID.',
          'Update LIMS sample status when configured.',
          'Send sample to laboratory processing area.',
        ],
        screens: ['nurse-portal'],
      },
    ],
    troubleshooting: [
      ['Patient not on queue', 'Front desk registration required first'],
      ['Cannot record vitals', 'Verify patient chart access permissions'],
      ['Bed shows occupied incorrectly', 'Contact ADT to release bed after discharge'],
    ],
  },
  {
    id: 'radiologist',
    role: 'Radiologist',
    login: 'Tef',
    password: '12345',
    icon: '📡',
    color: '#0891b2',
    colorLight: '#cffafe',
    portal: '/portal/radiology',
    hub: '/radiology',
    summary: 'Imaging worklist, payment verification, report authoring, and study finalization.',
    workflows: [
      {
        title: '1. Sign in & Radiology portal',
        intro: 'Portal shows pending studies and quick links to worklist.',
        steps: [
          'Sign in as <strong>Tef</strong> — <code>/portal/radiology</code>.',
          'Review pending studies, completed today, modality breakdown.',
          'Open worklist or validate-code shortcuts.',
        ],
        screens: ['login', 'rad-portal'],
      },
      {
        title: '2. Imaging worklist',
        intro: 'All ordered imaging studies appear with payment and status.',
        steps: [
          'Open <code>/radiology</code> worklist.',
          'Filter by date, modality (X-ray, US, CT), status.',
          'Identify paid vs pending-payment studies.',
          'Click study row to open detail and reporting workspace.',
        ],
        screens: ['rad-worklist'],
      },
      {
        title: '3. Verify payment & perform study',
        intro: 'Unpaid studies cannot be finalized.',
        steps: [
          'Confirm <strong>paid</strong> status or valid RAD payment code.',
          'If unpaid, direct patient to Cashier with doctor order slip.',
          'Perform imaging per clinical request.',
          'Upload images or link PACS when integrated.',
        ],
        screens: ['rad-worklist'],
      },
      {
        title: '4. Report authoring & finalization',
        intro: 'Structured reports sync to patient chart.',
        steps: [
          'Enter findings, impression, and recommendations.',
          'Use templates for common studies where available.',
          'Mark report <strong>Final</strong> — notifies ordering clinician.',
          'Print patient copy if required at radiology desk.',
        ],
        screens: ['rad-report'],
      },
    ],
    troubleshooting: [
      ['Study shows unpaid', 'Patient must pay at Cashier; validate RAD code'],
      ['Wrong department code', 'LAB codes cannot be used for radiology'],
      ['Cannot finalize', 'Complete all required report fields'],
    ],
  },
  {
    id: 'lab',
    role: 'Lab Technician',
    login: 'Sedrick',
    password: '12345',
    icon: '🔬',
    color: '#7c3aed',
    colorLight: '#ede9fe',
    portal: '/portal/lab',
    hub: '/laboratory',
    summary: 'LIMS requests, payment validation, structured results, and lab report delivery.',
    workflows: [
      {
        title: '1. Sign in & Laboratory portal',
        intro: 'Lab portal links LIMS, registry, templates, and order alerts.',
        steps: [
          'Sign in as <strong>Sedrick</strong> — <code>/portal/lab</code>.',
          'Review KPIs: pending tests, completed, today\'s volume.',
          'Open LIMS hub, Registry, or Order alerts.',
        ],
        screens: ['login', 'lab-portal'],
      },
      {
        title: '2. End-to-end lab pathway',
        intro: 'Standard flow from doctor order to printed report.',
        steps: [
          'Doctor orders test → Patient pays at Cashier (LAB code issued).',
          'Lab validates code → Sample collected → Results entered → Finalized.',
          'Report on patient chart; print copy for patient.',
        ],
        screens: ['lab-lims'],
      },
      {
        title: '3. Validate payment code',
        intro: 'Primary check-in when patient arrives at lab desk.',
        steps: [
          'Open <code>/laboratory/validate</code> or Registry → New test.',
          'Scan or type LAB code (e.g. <code>LAB-4829-K7HM3R9Q</code>).',
          'System verifies: paid, correct department, not duplicate.',
          'Open lab template with patient and order prefilled.',
        ],
        screens: ['lab-validate'],
      },
      {
        title: '4. Order alerts',
        intro: 'Doctor orders surface automatically for faster processing.',
        steps: [
          'Open <code>/laboratory/order-alerts</code>.',
          'Review unacknowledged orders from OPD, IPD, ER.',
          'Click <strong>Confirm & open template</strong>.',
          'Or handle via validate-code when patient presents at desk.',
        ],
        screens: ['lab-portal'],
      },
      {
        title: '5. Enter & finalize results',
        intro: 'Structured templates ensure consistent reporting.',
        steps: [
          'Enter parameters with reference ranges (Hb, WBC, etc.).',
          'Flag abnormal/critical values per SOP.',
          'Review and mark <strong>Final</strong>.',
          'Print report from registry or patient chart.',
        ],
        screens: ['lab-results'],
      },
      {
        title: '6. LIMS sample tracking',
        intro: 'Operational tracking complements the results registry.',
        steps: [
          'Open <code>/lims</code> for requests and samples.',
          'Update request status: submitted → in progress → complete.',
          'Record sample collection time and collector.',
          'Link sample ID to result entry.',
        ],
        screens: ['lab-lims'],
      },
    ],
    troubleshooting: [
      ['Payment required error', 'Send patient to Cashier with order slip'],
      ['Duplicate result', 'Result already exists for this order line'],
      ['Template not loading', 'Verify test mapped in LIMS configuration'],
    ],
  },
  {
    id: 'pharmacist',
    role: 'Pharmacist',
    login: 'Berinyuy',
    password: '12345',
    icon: '💊',
    color: '#10b981',
    colorLight: '#d1fae5',
    portal: '/portal/pharmacy',
    hub: '/pharmacy',
    summary: 'Prescription dispensing, payment verification, stock management, and patient counseling.',
    workflows: [
      {
        title: '1. Sign in & Pharmacy portal',
        intro: 'Pharmacy home shows dispensing queue and stock alerts.',
        steps: [
          'Sign in as <strong>Berinyuy</strong> — <code>/portal/pharmacy</code>.',
          'Review pending prescriptions and low-stock alerts.',
          'Open dispensing workspace at <code>/pharmacy</code>.',
        ],
        screens: ['login', 'pharm-portal'],
      },
      {
        title: '2. Dispensing queue',
        intro: 'Prescriptions arrive from doctor consultations after relevant payment.',
        steps: [
          'Search queue by patient name, Rx number, or date.',
          'Open prescription detail — verify drug, dose, duration.',
          'Check stock availability for each line item.',
          'Handle substitutions per hospital formulary if out of stock.',
        ],
        screens: ['pharm-dispense'],
      },
      {
        title: '3. Payment verification',
        intro: 'Pharmacy lines often require cashier payment before dispensing.',
        steps: [
          'Verify PHARM payment code or paid status on prescription.',
          'If unpaid, direct patient to Cashier with prescription slip.',
          'After payment confirmed, return to dispensing queue.',
        ],
        screens: ['pharm-verify'],
      },
      {
        title: '4. Dispense & counsel patient',
        intro: 'Completing dispensing updates inventory and closes the Rx.',
        steps: [
          'Record quantities dispensed and batch numbers if required.',
          'Click <strong>Mark dispensed</strong> — inventory decrements.',
          'Counsel patient: dosage, timing, food interactions, side effects.',
          'Print medication label or patient information leaflet.',
        ],
        screens: ['pharm-dispense'],
      },
      {
        title: '5. Stock & reporting',
        intro: 'Ongoing pharmacy operations beyond dispensing.',
        steps: [
          'Monitor low-stock and expiry alerts on portal dashboard.',
          'Use pharmacy reporting for consumption and expiry tracking.',
          'Raise procurement requisitions when stock is critical.',
        ],
        screens: ['pharm-portal'],
      },
    ],
    troubleshooting: [
      ['Rx not in queue', 'Doctor must save consultation prescription first'],
      ['Payment not verified', 'Patient pays pharmacy line at Cashier'],
      ['Insufficient stock', 'Partial dispense or substitute per policy'],
    ],
  },
];

module.exports = { PROFILES };
