'use strict';

function randomSuffix() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID().replace(/-/g, '').slice(0, 8).toUpperCase();
  }
  return Math.random().toString(36).slice(2, 10).toUpperCase();
}

/** Autogenerated journal reference — JE-YYYYMMDD-XXXXXXXX (Account_Core parity). */
function generateJournalReference(entryDate) {
  const raw = String(entryDate || '').trim().slice(0, 10);
  const d = /^\d{4}-\d{2}-\d{2}$/.test(raw) ? new Date(`${raw}T12:00:00`) : new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `JE-${y}${m}${day}-${randomSuffix()}`;
}

function todayIsoDate() {
  return new Date().toISOString().slice(0, 10);
}

module.exports = {
  generateJournalReference,
  todayIsoDate,
};
