'use strict';

/**
 * Pharmacy medications & materials — Service Catalog (category: pharmacy).
 * Prices in XAF. department_name = therapeutic / material class ("Used for" in UI).
 * subcategory = price list section.
 */
const PHARMACY_CATALOG_2026 = [
  // Analgesics & anti-inflammatory
  { sn: 1, section: 'Analgesics & Anti-inflammatory', name: 'Aspirin 300mg', price: 20, usedFor: 'Analgesic' },
  { sn: 2, section: 'Analgesics & Anti-inflammatory', name: 'Paracetamol 500mg', price: 20, usedFor: 'Analgesic' },
  { sn: 3, section: 'Analgesics & Anti-inflammatory', name: 'Paracetamol 500mg + Caffeine 30mg + Codeine 8mg', price: 100, usedFor: 'Analgesic' },
  { sn: 4, section: 'Analgesics & Anti-inflammatory', name: 'Paracetamol Syrup 120mg/5ml', price: 1000, usedFor: 'Analgesic' },
  { sn: 5, section: 'Analgesics & Anti-inflammatory', name: 'Diclofenac 100mg', price: 1500, usedFor: 'Analgesic' },
  { sn: 6, section: 'Analgesics & Anti-inflammatory', name: 'Ibuprofen 400mg', price: 100, usedFor: 'Analgesic' },
  { sn: 7, section: 'Analgesics & Anti-inflammatory', name: 'Efferalgan Codeine 500mg', price: 150, usedFor: 'Analgesic' },
  { sn: 8, section: 'Analgesics & Anti-inflammatory', name: 'Artifenac Forte (Diclofenac Sodium)', price: 100, usedFor: 'Analgesic' },
  { sn: 9, section: 'Analgesics & Anti-inflammatory', name: 'Ibuprofen', price: 20, usedFor: 'NSAID' },
  { sn: 10, section: 'Analgesics & Anti-inflammatory', name: 'Ibuprofen + Paracetamol 200/325mg', price: 100, usedFor: 'NSAID' },
  { sn: 11, section: 'Analgesics & Anti-inflammatory', name: 'Diclofenac 50mg Tablets', price: 20, usedFor: 'NSAID' },
  { sn: 12, section: 'Analgesics & Anti-inflammatory', name: 'Diclofenac 75mg Injection', price: 500, usedFor: 'NSAID' },
  { sn: 13, section: 'Analgesics & Anti-inflammatory', name: 'Diclofenac Gastro-resistant', price: 20, usedFor: 'NSAID' },
  { sn: 14, section: 'Analgesics & Anti-inflammatory', name: 'Diclofenac Potassium 50mg', price: 2000, usedFor: 'NSAID Topical' },
  { sn: 15, section: 'Analgesics & Anti-inflammatory', name: 'Voltarene Gel', price: 2500, usedFor: 'NSAID Topical' },
  { sn: 16, section: 'Analgesics & Anti-inflammatory', name: 'Analgin Injection', price: 1000, usedFor: 'Analgesic' },
  { sn: 17, section: 'Analgesics & Anti-inflammatory', name: 'Phenobarbital 100mg Tablet (Gardenal)', price: 100, usedFor: 'Anticonvulsant' },
  { sn: 18, section: 'Analgesics & Anti-inflammatory', name: 'Phenobarbital 200mg/ml Injection (Gardenal)', price: 500, usedFor: 'Anticonvulsant' },
  { sn: 19, section: 'Analgesics & Anti-inflammatory', name: 'Carbamazepine 200mg', price: 150, usedFor: 'Neuropathic Pain' },
  { sn: 20, section: 'Analgesics & Anti-inflammatory', name: 'Misoprostol', price: 250, usedFor: 'Uterine Stimulant' },
  // Antibiotics & antiparasitics
  { sn: 21, section: 'Antibiotics & Antiparasitics', name: 'Ampicillin Sodium 1g Injection', price: 2500, usedFor: 'Antibiotic' },
  { sn: 22, section: 'Antibiotics & Antiparasitics', name: 'Benzathine Penicillin 2.4 MIU (Bicillin)', price: 3500, usedFor: 'Antibiotic' },
  { sn: 23, section: 'Antibiotics & Antiparasitics', name: 'Crystalline Penicillin G 1M Units', price: 2500, usedFor: 'Antibiotic' },
  { sn: 24, section: 'Antibiotics & Antiparasitics', name: 'Penicillin V 250mg', price: 100, usedFor: 'Antibiotic' },
  { sn: 25, section: 'Antibiotics & Antiparasitics', name: 'Ceftriaxone 1g Inj + Water for Inj', price: 1000, usedFor: 'Antibiotic' },
  { sn: 26, section: 'Antibiotics & Antiparasitics', name: 'Cefixime Syrup', price: 2000, usedFor: 'Antibiotic' },
  { sn: 27, section: 'Antibiotics & Antiparasitics', name: 'Clarithromycin 500mg', price: 500, usedFor: 'Antibiotic' },
  { sn: 28, section: 'Antibiotics & Antiparasitics', name: 'Levofloxacin 500mg', price: 150, usedFor: 'Antibiotic' },
  { sn: 29, section: 'Antibiotics & Antiparasitics', name: 'Levofloxacin Perfusion Syrup', price: 2000, usedFor: 'Antibiotic' },
  { sn: 30, section: 'Antibiotics & Antiparasitics', name: 'Co-trimoxazole 240mg/5ml Syrup', price: 1000, usedFor: 'Antibiotic' },
  { sn: 31, section: 'Antibiotics & Antiparasitics', name: 'Co-trimoxazole 480mg (Bactrim)', price: 2000, usedFor: 'Antibiotic' },
  { sn: 32, section: 'Antibiotics & Antiparasitics', name: 'Metronidazole 500mg', price: 75, usedFor: 'Antibiotic' },
  { sn: 33, section: 'Antibiotics & Antiparasitics', name: 'Acyclovir 400mg Tablets', price: 250, usedFor: 'Antiviral' },
  { sn: 34, section: 'Antibiotics & Antiparasitics', name: 'Acyclovir Ointment', price: 3500, usedFor: 'Antiviral Topical' },
  { sn: 35, section: 'Antibiotics & Antiparasitics', name: 'Albendazole', price: 150, usedFor: 'Antihelminthic' },
  { sn: 36, section: 'Antibiotics & Antiparasitics', name: 'Fansidar 500mg', price: 500, usedFor: 'Antimalarial' },
  { sn: 37, section: 'Antibiotics & Antiparasitics', name: 'Coartem 20/120mg (Artemether)', price: 1500, usedFor: 'Antimalarial' },
  { sn: 38, section: 'Antibiotics & Antiparasitics', name: 'Coartem Dispersible Adult', price: 1500, usedFor: 'Antimalarial' },
  { sn: 39, section: 'Antibiotics & Antiparasitics', name: 'Artemether + Lumefantrine 20/120 mg', price: 2500, usedFor: 'Antimalarial' },
  { sn: 40, section: 'Antibiotics & Antiparasitics', name: 'Artemether + Lumefantrine 40/120 mg', price: 2000, usedFor: 'Antimalarial' },
  { sn: 41, section: 'Antibiotics & Antiparasitics', name: 'Artemether Injection 80mg', price: 1000, usedFor: 'Antimalarial' },
  // Antifungals
  { sn: 42, section: 'Antifungals', name: 'Fluconazole Suspension 50mg', price: 1500, usedFor: 'Antifungal' },
  { sn: 43, section: 'Antifungals', name: 'Fluconazole 200mg Capsule', price: 1000, usedFor: 'Antifungal' },
  { sn: 44, section: 'Antifungals', name: 'Miconazole Nitrate Cream 2% 15g', price: 1500, usedFor: 'Antifungal Topical' },
  { sn: 45, section: 'Antifungals', name: 'Nystatin Oral Suspension 100,000 Units/ml', price: 1000, usedFor: 'Antifungal' },
  { sn: 46, section: 'Antifungals', name: 'Nystatin Capsule 500,000 IU', price: 6000, usedFor: 'Antifungal' },
  { sn: 47, section: 'Antifungals', name: 'Nystatin Vaginal', price: 200, usedFor: 'Antifungal' },
  { sn: 48, section: 'Antifungals', name: 'Griseofulvin 500mg', price: 100, usedFor: 'Antifungal' },
  // Cardiovascular
  { sn: 49, section: 'Cardiovascular', name: 'Amlodipine 10mg', price: 100, usedFor: 'CCB Antihypertensive' },
  { sn: 50, section: 'Cardiovascular', name: 'Nifedipine 20mg', price: 25, usedFor: 'CCB Antihypertensive' },
  { sn: 51, section: 'Cardiovascular', name: 'Nifedipine Retard 20mg', price: 75, usedFor: 'CCB Antihypertensive' },
  { sn: 52, section: 'Cardiovascular', name: 'Captopril 25mg', price: 50, usedFor: 'ACE inhibitor' },
  { sn: 53, section: 'Cardiovascular', name: 'Lisinopril 10mg', price: 100, usedFor: 'ACE inhibitor' },
  { sn: 54, section: 'Cardiovascular', name: 'Losartan 50mg', price: 100, usedFor: 'ARB Antihypertensive' },
  { sn: 55, section: 'Cardiovascular', name: 'Telmisartan 40mg', price: 150, usedFor: 'ARB Antihypertensive' },
  { sn: 56, section: 'Cardiovascular', name: 'Hydralazine 50mg', price: 100, usedFor: 'Vasodilator' },
  { sn: 57, section: 'Cardiovascular', name: 'Bisoprolol 5mg', price: 100, usedFor: 'Beta Blocker' },
  { sn: 58, section: 'Cardiovascular', name: 'Propranolol 40mg', price: 50, usedFor: 'Beta Blocker' },
  { sn: 59, section: 'Cardiovascular', name: 'Aldactone 25mg (Spironolactone)', price: 75, usedFor: 'Diuretic' },
  { sn: 60, section: 'Cardiovascular', name: 'Frusemide 20mg/2ml Injection', price: 500, usedFor: 'Diuretic' },
  { sn: 61, section: 'Cardiovascular', name: 'HCTZ 25mg', price: 50, usedFor: 'Diuretic' },
  { sn: 62, section: 'Cardiovascular', name: 'HCTZ 50mg', price: 50, usedFor: 'Diuretic' },
  { sn: 63, section: 'Cardiovascular', name: 'Lasix 40mg (Furosemide)', price: 50, usedFor: 'Diuretic' },
  { sn: 64, section: 'Cardiovascular', name: 'Torsemide 20mg', price: 200, usedFor: 'Diuretic' },
  { sn: 65, section: 'Cardiovascular', name: 'Digoxin 0.25mg', price: 50, usedFor: 'Cardiac Glycoside' },
  { sn: 66, section: 'Cardiovascular', name: 'Atorvastatin 20mg', price: 175, usedFor: 'Statin' },
  // Gastrointestinal
  { sn: 67, section: 'Gastrointestinal', name: 'Omeprazole 20mg', price: 75, usedFor: 'PPI' },
  { sn: 68, section: 'Gastrointestinal', name: 'Pantoprazole 40mg', price: 200, usedFor: 'PPI' },
  { sn: 69, section: 'Gastrointestinal', name: 'Cimetidine 200mg Injection', price: 1500, usedFor: 'H2 Blocker' },
  { sn: 70, section: 'Gastrointestinal', name: 'Maalox Tablet', price: 2500, usedFor: 'Antacid' },
  { sn: 71, section: 'Gastrointestinal', name: 'Gestid Tablet', price: 6000, usedFor: 'Antacid' },
  { sn: 72, section: 'Gastrointestinal', name: 'Loperamide 2mg', price: 25, usedFor: 'Antidiarrheal' },
  { sn: 73, section: 'Gastrointestinal', name: 'ORS + Zinc', price: 100, usedFor: 'Rehydration' },
  { sn: 74, section: 'Gastrointestinal', name: 'Bisacodyl 5mg', price: 2000, usedFor: 'Laxative' },
  // Respiratory
  { sn: 75, section: 'Respiratory', name: 'Salbutamol Inhaler', price: 2500, usedFor: 'Bronchodilator' },
  { sn: 76, section: 'Respiratory', name: 'Salbutamol Nebules', price: 1000, usedFor: 'Bronchodilator' },
  { sn: 77, section: 'Respiratory', name: 'Chlorpheniramine Maleate 4mg', price: 10, usedFor: 'Antihistamine' },
  // Endocrine & metabolic
  { sn: 78, section: 'Endocrine & Metabolic', name: 'Glibenclamide 500mg (Daonil)', price: 20, usedFor: 'Antidiabetic' },
  { sn: 79, section: 'Endocrine & Metabolic', name: 'Diabetic Test Sugar Strips', price: 3500, usedFor: 'Diabetic Supplies' },
  { sn: 80, section: 'Endocrine & Metabolic', name: 'Metformin 500mg', price: 100, usedFor: 'Antidiabetic' },
  { sn: 81, section: 'Endocrine & Metabolic', name: 'Folic Acid 5mg', price: 20, usedFor: 'Vitamin Supplement' },
  { sn: 82, section: 'Endocrine & Metabolic', name: 'Vitamin B Complex', price: 50, usedFor: 'Vitamin Supplement' },
  { sn: 83, section: 'Endocrine & Metabolic', name: 'Vitamin B12 1000mcg', price: 100, usedFor: 'Vitamin Supplement' },
  { sn: 84, section: 'Endocrine & Metabolic', name: 'Multivitamin Syrup 200ml', price: 1500, usedFor: 'Vitamin Supplement' },
  { sn: 85, section: 'Endocrine & Metabolic', name: 'Multivitamin Baby Drops', price: 1200, usedFor: 'Vitamin Supplement' },
  { sn: 86, section: 'Endocrine & Metabolic', name: 'Revitalose or Equiv', price: 4500, usedFor: 'Vitamin Supplement' },
  { sn: 87, section: 'Endocrine & Metabolic', name: 'Aptamil (Baby Milk Supplement)', price: 5500, usedFor: 'Nutritional' },
  { sn: 88, section: 'Endocrine & Metabolic', name: 'Aptamil 400g', price: 1000, usedFor: 'Nutritional' },
  // Neurology
  { sn: 89, section: 'Neurology', name: 'Phenobarbital 100mg Injection', price: 1000, usedFor: 'Anticonvulsant' },
  // Obstetrics
  { sn: 90, section: 'Obstetrics', name: 'Oxytocin 10IU/ml Injection', price: 1500, usedFor: 'Uterotonic' },
  // Anaesthetics & emergency
  { sn: 91, section: 'Anaesthetics & Emergency', name: 'Adrenaline Injection', price: 500, usedFor: 'Emergency' },
  { sn: 92, section: 'Anaesthetics & Emergency', name: 'Dexamethasone 4mg Injection', price: 1000, usedFor: 'Corticosteroid' },
  { sn: 93, section: 'Anaesthetics & Emergency', name: 'Hydrocortisone Injection', price: 1500, usedFor: 'Corticosteroid' },
  { sn: 94, section: 'Anaesthetics & Emergency', name: 'Lidocaine 2% 50ml Injection', price: 1500, usedFor: 'Local Anaesthetic' },
  { sn: 95, section: 'Anaesthetics & Emergency', name: 'Lidocaine + Adrenaline Injection', price: 1000, usedFor: 'Local Anaesthetic' },
  { sn: 96, section: 'Anaesthetics & Emergency', name: 'Sodium Bicarbonate 250g', price: 500, usedFor: 'Electrolyte' },
  { sn: 97, section: 'Anaesthetics & Emergency', name: 'Sodium Bicarbonate Powder 100g', price: 500, usedFor: 'Electrolyte' },
  { sn: 98, section: 'Anaesthetics & Emergency', name: 'Potassium Chloride Injection', price: 1000, usedFor: 'Electrolyte' },
  // Intravenous fluids
  { sn: 99, section: 'Intravenous Fluids', name: 'Chloride de Sodium 0.9% 500ml (Normal Saline)', price: 1000, usedFor: 'IV Fluid' },
  { sn: 100, section: 'Intravenous Fluids', name: 'NS 0.9% 500ml', price: 1000, usedFor: 'IV Fluid' },
  { sn: 101, section: 'Intravenous Fluids', name: 'Glucose 5% 500ml', price: 1000, usedFor: 'IV Fluid' },
  { sn: 102, section: 'Intravenous Fluids', name: 'Glucose 10% 500ml', price: 1500, usedFor: 'IV Fluid' },
  { sn: 103, section: 'Intravenous Fluids', name: 'Glucose 50% 100ml', price: 2000, usedFor: 'IV Fluid' },
  { sn: 104, section: 'Intravenous Fluids', name: 'Glucose 5% + NaCl 0.9% 500ml', price: 1500, usedFor: 'IV Fluid' },
  { sn: 105, section: 'Intravenous Fluids', name: 'Ringer Lactate 500ml', price: 1500, usedFor: 'IV Fluid' },
  { sn: 106, section: 'Intravenous Fluids', name: "Darro's Solution 500ml", price: 4000, usedFor: 'IV Fluid' },
  { sn: 107, section: 'Intravenous Fluids', name: 'Water for Inj Injection 10ml', price: 100, usedFor: 'IV Fluid' },
  { sn: 108, section: 'Intravenous Fluids', name: 'Distilled Water for Preparation 1.5ml', price: 100, usedFor: 'IV Fluid' },
  // Consumables & surgical materials
  { sn: 109, section: 'Consumables & Surgical Materials', name: 'Cannula G18', price: 500, usedFor: 'Consumable' },
  { sn: 110, section: 'Consumables & Surgical Materials', name: 'Cannula G20', price: 500, usedFor: 'Consumable' },
  { sn: 111, section: 'Consumables & Surgical Materials', name: 'Cannula G22', price: 500, usedFor: 'Consumable' },
  { sn: 112, section: 'Consumables & Surgical Materials', name: 'Cannula G24', price: 500, usedFor: 'Consumable' },
  { sn: 113, section: 'Consumables & Surgical Materials', name: 'Gastric tube or NG tube', price: 500, usedFor: 'Consumable' },
  { sn: 114, section: 'Consumables & Surgical Materials', name: 'Drip Set', price: 500, usedFor: 'Consumable' },
  { sn: 115, section: 'Consumables & Surgical Materials', name: 'Syringe 2ml', price: 100, usedFor: 'Consumable' },
  { sn: 116, section: 'Consumables & Surgical Materials', name: 'Syringe 5ml (Auto)', price: 100, usedFor: 'Consumable' },
  { sn: 117, section: 'Consumables & Surgical Materials', name: 'Syringe 10ml', price: 100, usedFor: 'Consumable' },
  { sn: 118, section: 'Consumables & Surgical Materials', name: 'Syringe 20ml', price: 100, usedFor: 'Consumable' },
  { sn: 119, section: 'Consumables & Surgical Materials', name: 'Syringe 50ml', price: 100, usedFor: 'Consumable' },
  { sn: 120, section: 'Consumables & Surgical Materials', name: 'Needle (Hypodermic G21)', price: 500, usedFor: 'Consumable' },
  { sn: 121, section: 'Consumables & Surgical Materials', name: 'Urinary Bag (Paediatric/Adult)', price: 1000, usedFor: 'Consumable' },
  { sn: 122, section: 'Consumables & Surgical Materials', name: 'Urinary Catheter No. 14', price: 1500, usedFor: 'Consumable' },
  { sn: 123, section: 'Consumables & Surgical Materials', name: 'Urinary Catheter No. 16', price: 1500, usedFor: 'Consumable' },
  { sn: 124, section: 'Consumables & Surgical Materials', name: 'Nasogastric Tube No. 14', price: 1500, usedFor: 'Consumable' },
  { sn: 125, section: 'Consumables & Surgical Materials', name: 'Nasogastric Tube No. 16', price: 1500, usedFor: 'Consumable' },
  { sn: 126, section: 'Consumables & Surgical Materials', name: 'Surgical Gloves Latex 7.5', price: 1500, usedFor: 'Consumable' },
  { sn: 127, section: 'Consumables & Surgical Materials', name: 'Sterile Gloves No. 8', price: 1500, usedFor: 'Consumable' },
  { sn: 128, section: 'Consumables & Surgical Materials', name: 'Surgical Blade', price: 500, usedFor: 'Consumable' },
  { sn: 129, section: 'Consumables & Surgical Materials', name: 'Perforated Plaster', price: 3500, usedFor: 'Consumable' },
  { sn: 130, section: 'Consumables & Surgical Materials', name: 'Tongue Depressor', price: 500, usedFor: 'Consumable' },
  { sn: 131, section: 'Consumables & Surgical Materials', name: 'Haemoglobin Test Strips', price: 3500, usedFor: 'Diagnostic' },
  { sn: 132, section: 'Consumables & Surgical Materials', name: 'Atropine Paper', price: 50, usedFor: 'Consumable' },
  { sn: 133, section: 'Consumables & Surgical Materials', name: 'Large Urine Bags', price: 100, usedFor: 'Consumable' },
  { sn: 134, section: 'Consumables & Surgical Materials', name: 'Alcohol 70%', price: 3000, usedFor: 'Antiseptic' },
  { sn: 135, section: 'Consumables & Surgical Materials', name: 'Methylated Spirit', price: 4000, usedFor: 'Topical' },
  { sn: 136, section: 'Consumables & Surgical Materials', name: 'Lysol 100ml', price: 1500, usedFor: 'Topical' },
  { sn: 137, section: 'Consumables & Surgical Materials', name: 'Betadine', price: 1500, usedFor: 'Antiseptic' },
  { sn: 138, section: 'Consumables & Surgical Materials', name: 'Vitamin K1 10mg Injection', price: 3000, usedFor: 'Haemostatic' },
  { sn: 139, section: 'Consumables & Surgical Materials', name: 'Tranexamic Acid 500mg', price: 2500, usedFor: 'Haemostatic' },
];

const { upsertPharmacyCatalogRows } = require('./pharmacyCatalogFileImport');

/**
 * @param {import('mysql2/promise').Pool} pool
 * @param {{ deactivateMissing?: boolean, facilityId?: number }} [opts]
 */
async function seedPharmacyServiceCatalog(pool, opts = {}) {
  return upsertPharmacyCatalogRows(pool, PHARMACY_CATALOG_2026, { ...opts, matchBySnCpt: true });
}

module.exports = {
  PHARMACY_CATALOG_2026,
  seedPharmacyServiceCatalog,
};
