'use strict';

/**
 * Lobby display — ZAIZENS services (EN + FR).
 * Photos: public/call-queue/photos/ (run scripts/fetch-call-queue-photos.js to refresh).
 */
const TSSF_CALL_QUEUE_ADS = [
  {
    type: 'message',
    icon: 'fa-hospital-o',
    titleEn: 'ZAIZENS',
    titleFr: 'ZAIZENS',
    subtitleEn: 'ZAIZENS Integrated HMS',
    subtitleFr: 'HMS intégré ZAIZENS',
    bodyEn: 'Consultation, OPD, IPD, maternity, pharmacy, laboratory, imaging — one mission of care.',
    bodyFr: 'Consultation, OPD, hospitalisation, maternité, pharmacie, laboratoire, imagerie — une seule mission de soins.',
    accent: '#0891b2',
  },
  {
    type: 'image',
    icon: 'fa-stethoscope',
    titleEn: 'Consultation',
    titleFr: 'Consultation',
    subtitleEn: 'Doctor–patient visit · examination · care plan',
    subtitleFr: 'Visite médecin–patient · examen · plan de soins',
    image: '/call-queue/ads/consultation.svg',
    imageFallback: '/call-queue/ads/hospital-poster.svg',
    accent: '#2563eb',
  },
  {
    type: 'image',
    icon: 'fa-list-alt',
    titleEn: 'OPD — Outpatient',
    titleFr: 'OPD — Consultations externes',
    subtitleEn: 'Registration · queue · same-day care',
    subtitleFr: "Accueil · file d'attente · soins le jour même",
    image: '/call-queue/ads/opd.svg',
    imageFallback: '/call-queue/ads/hospital-poster.svg',
    accent: '#0ea5e9',
  },
  {
    type: 'image',
    icon: 'fa-bed',
    titleEn: 'IPD — Inpatient',
    titleFr: 'IPD — Hospitalisation',
    subtitleEn: 'Ward care · monitoring · treatment',
    subtitleFr: 'Soins en service · surveillance · traitement',
    image: '/call-queue/ads/ipd.svg',
    imageFallback: '/call-queue/ads/hospital-poster.svg',
    accent: '#6366f1',
  },
  {
    type: 'image',
    icon: 'fa-female',
    titleEn: 'Maternity',
    titleFr: 'Maternité',
    subtitleEn: 'Antenatal · delivery · postnatal support',
    subtitleFr: 'Prénatal · accouchement · suivi postnatal',
    image: '/call-queue/ads/maternity.svg',
    imageFallback: '/call-queue/ads/hospital-poster.svg',
    accent: '#9d174d',
  },
  {
    type: 'image',
    icon: 'fa-medkit',
    titleEn: 'Pharmacy',
    titleFr: 'Pharmacie',
    subtitleEn: 'Dispensing · counselling · essential medicines',
    subtitleFr: 'Dispensation · conseil · médicaments essentiels',
    image: '/call-queue/ads/pharmacy.svg',
    imageFallback: '/call-queue/ads/hospital-poster.svg',
    accent: '#b45309',
  },
  {
    type: 'image',
    icon: 'fa-flask',
    titleEn: 'Laboratory',
    titleFr: 'Laboratoire',
    subtitleEn: 'Haematology · biochemistry · rapid tests',
    subtitleFr: 'Hématologie · biochimie · tests rapides',
    image: '/call-queue/ads/laboratory.svg',
    imageFallback: '/call-queue/ads/laboratory.svg',
    accent: '#7c3aed',
  },
  {
    type: 'image',
    icon: 'fa-user-md',
    titleEn: 'Medical doctors',
    titleFr: 'Médecins',
    subtitleEn: 'Specialists & general practice',
    subtitleFr: 'Spécialistes et médecine générale',
    image: '/call-queue/ads/doctors.svg',
    imageFallback: '/call-queue/ads/doctors.svg',
    accent: '#1d4ed8',
  },
  {
    type: 'image',
    icon: 'fa-heartbeat',
    titleEn: 'Nurses',
    titleFr: 'Infirmiers / infirmières',
    subtitleEn: 'Triage · bedside care · patient support',
    subtitleFr: 'Triage · soins au lit · accompagnement',
    image: '/call-queue/ads/nurses.svg',
    imageFallback: '/call-queue/ads/nurses.svg',
    accent: '#059669',
  },
  {
    type: 'image',
    icon: 'fa-picture-o',
    titleEn: 'Medical imaging',
    titleFr: 'Imagerie médicale',
    subtitleEn: 'X-ray · ultrasound · ECG',
    subtitleFr: 'Radiographie · échographie · ECG',
    image: '/call-queue/ads/radiology.svg',
    imageFallback: '/call-queue/ads/radiology.svg',
    accent: '#0e7490',
  },
];

module.exports = { TSSF_CALL_QUEUE_ADS };
